server:
  port: 8082

service:
  scheduling:
    fixer:
      cron: "0 5 0 * * *"
      timezone: "GMT"
  base-currency: &base-currency-code "EUR"
  spread:
    default: 2.75
    base-currency:
      code: *base-currency-code
      value: 0
    mapping:
      JPY: 3.25
      HKD: 3.25
      KRW: 3.25
      MYR: 4.50
      INR: 4.50
      MXN: 4.50
      RUB: 6.00
      CNY: 6.00
      ZAR: 6.00

providers:
  fixer:
    api-key: 227a4ef208d9a9ec37d6a2b3138acce5
    latest-path: http://data.fixer.io/api/latest

spring:
  datasource:
    url: jdbc:h2:mem:xchg_rates
#    url: jdbc:h2:file:~/xchg/rates
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
